### PR TITLE
Just idea: Recursive decorating function

### PR DESCRIPTION
**Pull request by webdevium**
I tried to make a variant of the methods that allow you to assign additional conditions to the internal recursive query that is used in the `unionAll()`

This will allow you to add additional constraints on the selection in a recursive context so as not to pull in large amounts of data.

### CODE REVIEW

**Comment by staudenmeir** [comment]
Thanks, I'll take a look.

Do you have a specific use case for this feature in your application?

**Comment by webdevium** [comment]
Yeap.  Perhaps you could remember
#46

In such cases, it was necessary to add an additional condition in order to get not all descendants. Just as an example.

**Comment by webdevium** [comment]
I'll try, of course

**Comment by webdevium** [comment]
If I understood you correctly, it will be like this

**Comment by staudenmeir** [comment]
Perfect, thanks.

**Comment by webdevium** [comment]
Can I turn off tests for `sqlsrv`? :)

**Comment by staudenmeir** [comment]
I'll look into the errors.

**Comment by webdevium** [comment]
Tnx!

**Comment by staudenmeir** [comment]
Thanks! I renamed the method to `withRecursiveQueryConstraint()` and released a new version.

**Pull request merged**
