### PR TITLE
Add scope for querying without children

### PR DESCRIPTION
**Pull request by l3aro**
Add query scope for selecting top most children that doesn't have any children below them

### CODE REVIEW

**Comment by staudenmeir** [comment]
Hi @l3aro,
Thanks for your PR. Please call the `isLeaf()` scope instead of duplicating its code.

**Comment by l3aro** [comment]
> Hi @l3aro, Thanks for your PR. Please call the `isLeaf()` scope instead of duplicating its code.

You're right, somehow I'm not aware of that method

**Comment by staudenmeir** [comment]
Sorry, that was a misunderstanding. I thought you knew about the `isLeaf()`scope and wanted to add an alias with a name that's easier to understand.

I think it's a good idea to have this alias. I would only change the method body so that it calls the `isLeaf()` scope instead of implementing the same code (`$keys = ...`).

**Comment by l3aro** [comment]
> Sorry, that was a misunderstanding. I thought you knew about the `isLeaf()` scope and wanted to add an alias with a name that's easier to understand.
> 
> I think it's a good idea to have this alias. I would only change the method body so that it calls the `isLeaf()` scope instead of implementing the same code (`$keys = ...`).

Sure things! I did update as you recommend. Pls have a look and see if anything else missing

**Comment by staudenmeir** [comment]
Thanks!

**Comment by staudenmeir** [comment]
I released a new version.

**Pull request merged**
